import PDFDocument from 'pdfkit';
import type { ScreenRatioRow } from '@quotezen/calc';
import type { QuoteWithChildren } from './repository.js';
import { DEFAULT_ASSUMPTIONS, DEFAULT_EXCLUSIONS, DEFAULT_TERMS, buildDescriptions } from './outputs.js';

const money = (v: { toString(): string } | null | undefined, code: string): string =>
  `${code} ${Number(v ?? 0).toLocaleString('en-AU', { minimumFractionDigits: 2 })}`;

/**
 * Render a client-facing quote PDF (offline, via pdfkit — no headless browser). Returns the full
 * document as a Buffer so it can be sent in one response.
 */
export const buildQuotePdf = (
  quote: QuoteWithChildren,
  ratios?: readonly ScreenRatioRow[],
): Promise<Buffer> =>
  new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const code = quote.currency?.code ?? 'AUD';
    const heading = (t: string) => doc.moveDown(0.6).fontSize(13).fillColor('#111').text(t).moveDown(0.2);
    const line = (l: string, r: string) => {
      const y = doc.y;
      doc.fontSize(10).fillColor('#333').text(l, 50, y, { width: 360 });
      doc.text(r, 410, y, { width: 135, align: 'right' });
    };

    // Header
    doc.fontSize(22).fillColor('#6d6bf6').text('QuoteZen', { continued: true }).fillColor('#999').fontSize(12).text('  Seen Technology');
    doc.moveDown(0.3).fontSize(16).fillColor('#111').text(`Quote ${quote.jobReference}`);
    doc.fontSize(10).fillColor('#666')
      .text(`Client: ${quote.client?.name ?? '—'}`)
      .text(`Status: ${quote.status}`)
      .text(`Currency: ${code}`);
    if (quote.validUntil) doc.text(`Valid until: ${new Date(quote.validUntil).toLocaleDateString()}`);

    // LED screens — deterministic descriptions (P1-18.1)
    const descriptions = new Map(buildDescriptions(quote, ratios).map((d) => [d.screenId, d.description]));
    if (quote.ledScreens.length > 0) {
      heading('LED screens');
      for (const s of quote.ledScreens) {
        line(descriptions.get(s.id.toString()) ?? s.screenName ?? 'LED screen', money(s.priceTotal, code));
      }
    }
    // LCD screens
    if (quote.lcdScreens.length > 0) {
      heading('LCD displays');
      for (const s of quote.lcdScreens) line(s.screenName ?? 'LCD', money(s.priceTotal, code));
    }
    // Licences
    if (quote.licences.length > 0) {
      heading('Licences & support (annual)');
      for (const l of quote.licences) {
        line(`${l.screenType} · ${l.tier} · ${l.qty} screen(s)${l.isInteractive ? ' · interactive' : ''}`, '');
      }
    }

    // Totals
    heading('Totals');
    line('Equipment', money(quote.totalEquipment, code));
    line('Services', money(quote.totalServices, code));
    line('Recurring / yr', money(quote.totalRecurring, code));
    doc.moveDown(0.2);
    doc.fontSize(13).fillColor('#111');
    const y = doc.y;
    doc.text('Grand total', 50, y, { width: 360 });
    doc.text(money(quote.grandTotal, code), 410, y, { width: 135, align: 'right' });

    // Assumptions / exclusions / terms (P1-18.2, BR-090/091)
    // Render the quote's STORED terms grouped by kind, falling back to the DEFAULT_* constants for
    // any group with no stored rows — never a silently-blank section.
    const bullets = (title: string, items: readonly string[]) => {
      heading(title);
      doc.fontSize(9).fillColor('#444');
      for (const it of items) doc.text(`•  ${it}`, { width: 495 });
    };
    const storedOf = (kind: string): string[] =>
      quote.terms.filter((t) => t.kind === kind).map((t) => t.text);
    const grouped = (kind: string, fallback: readonly string[]): readonly string[] => {
      const stored = storedOf(kind);
      return stored.length > 0 ? stored : fallback;
    };
    bullets('Assumptions', grouped('assumption', DEFAULT_ASSUMPTIONS));
    bullets('Exclusions', grouped('exclusion', DEFAULT_EXCLUSIONS));
    bullets('Terms & conditions', grouped('term', DEFAULT_TERMS));

    doc.moveDown(1.5).fontSize(8).fillColor('#999')
      .text('All prices ex-GST. Generated by QuoteZen.', { align: 'center' });

    doc.end();
  });
